### ISSUE TITLE
led.py not working

### ISSUE THREAD

**Issue by aa0pb** [tcaserza/nhlgoallight#3]
Howdy,
Working on setting one up and I get an Adafruit_NeoPixel name not defined error when I run test.py.

This is a fresh install of Raspberry Pi OS Lite on a new RPi 4.

I have tested the lights with my own test code and they are working, also the sound is working.  This is the last part to get it fully 100%

Code from led.py
--------------------------
def run_goal_light():
strip = Adafruit_NeoPixel(LED_COUNT, LED_PIN, LED_FREQ_HZ, LED_DMA, LED_INVERT, LED_BRIGHTNESS, LED_CHANNEL)
strip.begin()
theaterChase(strip,Color(153, 0, 153),50,500)
def clear_goal_light():
strip = Adafruit_NeoPixel(LED_COUNT, LED_PIN, LED_FREQ_HZ, LED_DMA, LED_INVERT, LED_BRIGHTNESS, LED_CHANNEL)
strip.begin()
colorWipe(strip, Color(0,0,0), 10)

And here is the error when I try test.py
--------------------------------------
pi@raspberrypi:~/nhlgoallight $ sudo python3 test.py
GOAL HORN
GOAL LAMP
Process Process-1:
Traceback (most recent call last):
File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
self.run()
File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
self._target(*self._args, **self._kwargs)
File "/home/pi/nhlgoallight/led.py", line 82, in run_goal_light
strip = Adafruit_NeoPixel(LED_COUNT, LED_PIN, LED_FREQ_HZ, LED_DMA, LED_INVERT, LED_BRIGHTNESS, LED_CHANNEL)
NameError: name 'Adafruit_NeoPixel' is not defined
Audio codec mp3float channels 2 samplerate 44100 bitspersample 16
Subtitle count: 0, state: off, index: 1, delay: 0
have a nice day ;)
Traceback (most recent call last):
File "test.py", line 3, in 
play_goal_horn()
File "/home/pi/nhlgoallight/nhlgoallight.py", line 82, in play_goal_horn
clear_goal_light()
File "/home/pi/nhlgoallight/led.py", line 89, in clear_goal_light
strip = Adafruit_NeoPixel(LED_COUNT, LED_PIN, LED_FREQ_HZ, LED_DMA, LED_INVERT, LED_BRIGHTNESS, LED_CHANNEL)
NameError: name 'Adafruit_NeoPixel' is not defined

Thanks for the project and any help.

**Comment by dword4** [comment]
The issue seems to be coming from https://github.com/adafruit/Adafruit_CircuitPython_NeoPixel/commit/d82df61dfababfbe0dc9fd00ca7dc9105bc2aa56 where there is a naming change implemented that breaks the way this repo interacts with that python package

**Comment by aa0pb** [comment]
dword4 - thanks for that. 
I did update the ley.py file to neopixel I get "NameError: name 'neopixel' is not defined"
If I use NeoPixel I get "TypeError: __init__() takes 3 positional arguments but 8 were given"

Sorry for the back and forth, still learning Python
